ALTER TABLE SYS_AUTHORITIES_RESOURCES 
  DROP CONSTRAINT FK_SYS_AUTH_REFERENCE_SYS_AUTH; 
ALTER TABLE SYS_AUTHORITIES_RESOURCES 
  DROP CONSTRAINT FK_SYS_AUTH_REFERENCE_SYS_RESO; 
ALTER TABLE SYS_RESOURCES 
  DROP CONSTRAINT FK_SYS_RESO_REFERENCE_SYS_MODU; 
ALTER TABLE SYS_ROLES_AUTHORITIES 
  DROP CONSTRAINT FK_SYS_ROLE_REFERENCE_SYS_ROLE; 
ALTER TABLE SYS_ROLES_AUTHORITIES 
  DROP CONSTRAINT FK_SYS_ROLE_REFERENCE_SYS_AUTH; 
ALTER TABLE SYS_ROLES_MOUDLES 
  DROP CONSTRAINT FK_SYS_ROLE_REFERENCE_SYS_MODU; 
ALTER TABLE SYS_ROLES_MOUDLES 
  DROP CONSTRAINT FK_S_ROLE_REFERENCE_SYS_ROLE; 
ALTER TABLE SYS_USERS_ROLES 
  DROP CONSTRAINT FK_SYS_USER_REFERENCE_SYS_USER; 
ALTER TABLE SYS_USERS_ROLES 
  DROP CONSTRAINT FK_SYS_USER_REFERENCE_SYS_ROLE; 
DROP TABLE PERSISTENT_LOGINS CASCADE CONSTRAINTS; 
DROP TABLE SYS_AUTHORITIES CASCADE CONSTRAINTS; 
DROP TABLE SYS_AUTHORITIES_RESOURCES CASCADE CONSTRAINTS; 
DROP TABLE SYS_MODULES CASCADE CONSTRAINTS; 
DROP TABLE SYS_RESOURCES CASCADE CONSTRAINTS; 
DROP TABLE SYS_ROLES CASCADE CONSTRAINTS; 
DROP TABLE SYS_ROLES_AUTHORITIES CASCADE CONSTRAINTS; 
DROP TABLE SYS_ROLES_MOUDLES CASCADE CONSTRAINTS; 
DROP TABLE SYS_USERS CASCADE CONSTRAINTS; 
DROP TABLE SYS_USERS_ROLES CASCADE CONSTRAINTS; 
/*==============================================================*/ 
/* Table: PERSISTENT_LOGINS                   */ 
/*==============================================================*/ 
CREATE TABLE PERSISTENT_LOGINS ( 
  USERNAME       VARCHAR(64), 
  SERIES        VARCHAR(64)          NOT NULL, 
  TOKEN        VARCHAR(64), 
  LAST_USED      TIMESTAMP, 
  CONSTRAINT PK_PERSISTENT_LOGINS PRIMARY KEY (SERIES) 
); 
COMMENT ON TABLE PERSISTENT_LOGINS IS 
'Spring Remember me 持久化'; 
/*==============================================================*/ 
/* Table: SYS_AUTHORITIES                    */ 
/*==============================================================*/ 
CREATE TABLE SYS_AUTHORITIES ( 
  AUTHORITY_ID     VARCHAR(100)          NOT NULL, 
  AUTHORITY_MARK    VARCHAR(100), 
  AUTHORITY_NAME    VARCHAR(100)          NOT NULL, 
  AUTHORITY_DESC    VARCHAR(200), 
  MESSAGE       VARCHAR(100), 
  ENABLE        INT(100), 
  ISSYS        INT(100), 
  MODULE_ID      VARCHAR(100), 
  CONSTRAINT PK_SYS_AUTHORITIES PRIMARY KEY (AUTHORITY_ID) 
); 
/*==============================================================*/ 
/* Table: SYS_AUTHORITIES_RESOURCES               */ 
/*==============================================================*/ 
CREATE TABLE SYS_AUTHORITIES_RESOURCES ( 
  ID          VARCHAR(100)          NOT NULL, 
  RESOURCE_ID     VARCHAR(100)          NOT NULL, 
  AUTHORITY_ID     VARCHAR(100)          NOT NULL, 
  CONSTRAINT PK_SYS_AUTHORITIES_RESOURCES PRIMARY KEY (ID) 
); 
/*==============================================================*/ 
/* Table: SYS_MODULES                      */ 
/*==============================================================*/ 
CREATE TABLE SYS_MODULES ( 
  MODULE_ID      VARCHAR(100)          NOT NULL, 
  MODULE_NAME     VARCHAR(100)          NOT NULL, 
  MODULE_DESC     VARCHAR(200), 
  MODULE_TYPE     VARCHAR(100), 
  PARENT        VARCHAR(100), 
  MODULE_URL      VARCHAR(100), 
  I_LEVEL       INT(2), 
  LEAF         INT(2), 
  APPLICATION     VARCHAR(100), 
  CONTROLLER      VARCHAR(100), 
  ENABLE        INT(1), 
  PRIORITY       INT(1), 
  CONSTRAINT PK_SYS_MODULES PRIMARY KEY (MODULE_ID) 
); 
COMMENT ON COLUMN SYS_MODULES.I_LEVEL IS 
'1'; 
/*==============================================================*/ 
/* Table: SYS_RESOURCES                     */ 
/*==============================================================*/ 
CREATE TABLE SYS_RESOURCES ( 
  RESOURCE_ID     VARCHAR(100)          NOT NULL, 
  RESOURCE_TYPE    VARCHAR(100), 
  RESOURCE_NAME    VARCHAR(100), 
  RESOURCE_DESC    VARCHAR(200), 
  RESOURCE_PATH    VARCHAR(200), 
  PRIORITY       VARCHAR(100), 
  ENABLE        INT(1), 
  ISSYS        INT(1), 
  MODULE_ID      VARCHAR(100), 
  CONSTRAINT PK_SYS_RESOURCES PRIMARY KEY (RESOURCE_ID) 
); 
COMMENT ON COLUMN SYS_RESOURCES.RESOURCE_TYPE IS 
'URL,METHOD'; 
/*==============================================================*/ 
/* Table: SYS_ROLES                       */ 
/*==============================================================*/ 
CREATE TABLE SYS_ROLES ( 
  ROLE_ID       VARCHAR(100)          NOT NULL, 
  ROLE_NAME      VARCHAR(100), 
  ROLE_DESC      VARCHAR(200), 
  ENABLE        INT(1), 
  ISSYS        INT(1), 
  MODULE_ID      VARCHAR(100), 
  CONSTRAINT PK_SYS_ROLES PRIMARY KEY (ROLE_ID) 
); 
/*==============================================================*/ 
/* Table: SYS_ROLES_AUTHORITIES                 */ 
/*==============================================================*/ 
CREATE TABLE SYS_ROLES_AUTHORITIES ( 
  ID          VARCHAR(100)          NOT NULL, 
  AUTHORITY_ID     VARCHAR(100)          NOT NULL, 
  ROLE_ID       VARCHAR(100)          NOT NULL, 
  CONSTRAINT PK_SYS_ROLES_AUTHORITIES PRIMARY KEY (ID) 
); 
/*==============================================================*/ 
/* Table: SYS_ROLES_MOUDLES                   */ 
/*==============================================================*/ 
CREATE TABLE SYS_ROLES_MOUDLES ( 
  ID          VARCHAR(100)          NOT NULL, 
  MODULE_ID      VARCHAR(100)          NOT NULL, 
  ROLE_ID       VARCHAR(100)          NOT NULL, 
  CONSTRAINT PK_SYS_ROLES_MOUDLES PRIMARY KEY (ID) 
); 
COMMENT ON TABLE SYS_ROLES_MOUDLES IS 
'控制角色对模块的访问权，主要用于生成菜单'; 
/*==============================================================*/ 
/* Table: SYS_USERS                       */ 
/*==============================================================*/ 
CREATE TABLE SYS_USERS ( 
  USER_ID       VARCHAR(100)          NOT NULL, 
  USERNAME       VARCHAR(100)          NOT NULL, 
  NAME         VARCHAR(100), 
  PASSWORD       VARCHAR(100)          NOT NULL, 
  DT_CREATE      DATE, 
  LAST_LOGIN      DATE, 
  DEADLINE       DATE, 
  LOGIN_IP       VARCHAR(100), 
  V_QZJGID       VARCHAR(100), 
  V_QZJGMC       VARCHAR(100), 
  DEP_ID        VARCHAR(100), 
  DEP_NAME       VARCHAR(100), 
  ENABLED       INT(100), 
  ACCOUNT_NON_EXPIRED INT(2), 
  ACCOUNT_NON_LOCKED  INT(2), 
  CREDENTIALS_NON_EXPIRED INT(2), 
  CONSTRAINT PK_SYS_USERS PRIMARY KEY (USER_ID) 
); 
/*==============================================================*/ 
/* Table: SYS_USERS_ROLES                    */ 
/*==============================================================*/
CREATE TABLE SYS_USERS_ROLES ( 
  ID          VARCHAR(100)          NOT NULL, 
  ROLE_ID       VARCHAR(100)          NOT NULL, 
  USER_ID       VARCHAR(100)          NOT NULL, 
  CONSTRAINT PK_SYS_USERS_ROLES PRIMARY KEY (ID) 
); 
ALTER TABLE SYS_AUTHORITIES_RESOURCES 
  ADD CONSTRAINT FK_SYS_AUTH_REFERENCE_SYS_AUTH FOREIGN KEY (AUTHORITY_ID) 
   REFERENCES SYS_AUTHORITIES (AUTHORITY_ID); 
ALTER TABLE SYS_AUTHORITIES_RESOURCES 
  ADD CONSTRAINT FK_SYS_AUTH_REFERENCE_SYS_RESO FOREIGN KEY (RESOURCE_ID) 
   REFERENCES SYS_RESOURCES (RESOURCE_ID); 
ALTER TABLE SYS_RESOURCES 
  ADD CONSTRAINT FK_SYS_RESO_REFERENCE_SYS_MODU FOREIGN KEY (MODULE_ID) 
   REFERENCES SYS_MODULES (MODULE_ID); 
ALTER TABLE SYS_ROLES_AUTHORITIES 
  ADD CONSTRAINT FK_SYS_ROLE_REFERENCE_SYS_ROLE FOREIGN KEY (ROLE_ID) 
   REFERENCES SYS_ROLES (ROLE_ID); 
ALTER TABLE SYS_ROLES_AUTHORITIES 
  ADD CONSTRAINT FK_SYS_ROLE_REFERENCE_SYS_AUTH FOREIGN KEY (AUTHORITY_ID) 
   REFERENCES SYS_AUTHORITIES (AUTHORITY_ID); 
ALTER TABLE SYS_ROLES_MOUDLES 
  ADD CONSTRAINT FK_SYS_ROLE_REFERENCE_SYS_MODU FOREIGN KEY (MODULE_ID) 
   REFERENCES SYS_MODULES (MODULE_ID); 
ALTER TABLE SYS_ROLES_MOUDLES 
  ADD CONSTRAINT FK_S_ROLE_REFERENCE_SYS_ROLE FOREIGN KEY (ROLE_ID) 
   REFERENCES SYS_ROLES (ROLE_ID); 
ALTER TABLE SYS_USERS_ROLES 
  ADD CONSTRAINT FK_SYS_USER_REFERENCE_SYS_USER FOREIGN KEY (USER_ID) 
   REFERENCES SYS_USERS (USER_ID); 
ALTER TABLE SYS_USERS_ROLES 
  ADD CONSTRAINT FK_SYS_USER_REFERENCE_SYS_ROLE FOREIGN KEY (ROLE_ID) 
   REFERENCES SYS_ROLES (ROLE_ID);